# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'kleon.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QMainWindow,
    QPlainTextEdit, QProgressBar, QSizePolicy, QWidget)

class Ui_Kleon(object):
    def setupUi(self, Kleon):
        if not Kleon.objectName():
            Kleon.setObjectName(u"Kleon")
        Kleon.resize(940, 640)
        Kleon.setDockOptions(QMainWindow.DockOption.AllowTabbedDocks|QMainWindow.DockOption.AnimatedDocks)
        self.centralwidget = QWidget(Kleon)
        self.centralwidget.setObjectName(u"centralwidget")
        self.opsBox = QGroupBox(self.centralwidget)
        self.opsBox.setObjectName(u"opsBox")
        self.opsBox.setGeometry(QRect(20, 10, 201, 551))
        font = QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.opsBox.setFont(font)
        self.opsBox.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.dnfOpt = QCheckBox(self.opsBox)
        self.dnfOpt.setObjectName(u"dnfOpt")
        self.dnfOpt.setGeometry(QRect(20, 120, 171, 22))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setItalic(False)
        self.dnfOpt.setFont(font1)
        self.dnfOpt.setChecked(True)
        self.systemdOpt = QCheckBox(self.opsBox)
        self.systemdOpt.setObjectName(u"systemdOpt")
        self.systemdOpt.setGeometry(QRect(20, 210, 171, 22))
        self.systemdOpt.setFont(font1)
        self.systemdOpt.setChecked(True)
        self.bashOpt = QCheckBox(self.opsBox)
        self.bashOpt.setObjectName(u"bashOpt")
        self.bashOpt.setGeometry(QRect(20, 390, 171, 22))
        self.bashOpt.setFont(font1)
        self.bashOpt.setChecked(True)
        self.cacheOpt = QCheckBox(self.opsBox)
        self.cacheOpt.setObjectName(u"cacheOpt")
        self.cacheOpt.setGeometry(QRect(20, 420, 171, 22))
        self.cacheOpt.setFont(font1)
        self.cacheOpt.setChecked(True)
        self.flatpakOpt = QCheckBox(self.opsBox)
        self.flatpakOpt.setObjectName(u"flatpakOpt")
        self.flatpakOpt.setGeometry(QRect(20, 150, 171, 22))
        self.flatpakOpt.setFont(font1)
        self.flatpakOpt.setChecked(True)
        self.coredumpOpt = QCheckBox(self.opsBox)
        self.coredumpOpt.setObjectName(u"coredumpOpt")
        self.coredumpOpt.setGeometry(QRect(20, 270, 171, 22))
        self.coredumpOpt.setFont(font1)
        self.coredumpOpt.setChecked(True)
        self.packagekitOpt = QCheckBox(self.opsBox)
        self.packagekitOpt.setObjectName(u"packagekitOpt")
        self.packagekitOpt.setGeometry(QRect(20, 300, 171, 22))
        self.packagekitOpt.setFont(font1)
        self.packagekitOpt.setChecked(True)
        self.tmpOpt = QCheckBox(self.opsBox)
        self.tmpOpt.setObjectName(u"tmpOpt")
        self.tmpOpt.setGeometry(QRect(20, 330, 171, 22))
        self.tmpOpt.setFont(font1)
        self.tmpOpt.setChecked(True)
        self.logsOpt = QCheckBox(self.opsBox)
        self.logsOpt.setObjectName(u"logsOpt")
        self.logsOpt.setGeometry(QRect(20, 240, 171, 22))
        self.logsOpt.setFont(font1)
        self.logsOpt.setChecked(True)
        self.abrtOpt = QCheckBox(self.opsBox)
        self.abrtOpt.setObjectName(u"abrtOpt")
        self.abrtOpt.setGeometry(QRect(20, 360, 171, 22))
        self.abrtOpt.setFont(font1)
        self.abrtOpt.setChecked(True)
        self.kernelOpt = QCheckBox(self.opsBox)
        self.kernelOpt.setObjectName(u"kernelOpt")
        self.kernelOpt.setGeometry(QRect(20, 180, 171, 22))
        self.kernelOpt.setFont(font1)
        self.kernelOpt.setChecked(True)
        self.recentOpt = QCheckBox(self.opsBox)
        self.recentOpt.setObjectName(u"recentOpt")
        self.recentOpt.setGeometry(QRect(20, 450, 171, 22))
        self.recentOpt.setFont(font1)
        self.recentOpt.setChecked(True)
        self.browserOpt = QCheckBox(self.opsBox)
        self.browserOpt.setObjectName(u"browserOpt")
        self.browserOpt.setGeometry(QRect(20, 480, 171, 22))
        self.browserOpt.setFont(font1)
        self.browserOpt.setChecked(True)
        self.passwordOpt = QCheckBox(self.opsBox)
        self.passwordOpt.setObjectName(u"passwordOpt")
        self.passwordOpt.setGeometry(QRect(40, 510, 151, 22))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setItalic(True)
        self.passwordOpt.setFont(font2)
        self.passwordOpt.setChecked(False)
        self.logBox = QGroupBox(self.centralwidget)
        self.logBox.setObjectName(u"logBox")
        self.logBox.setGeometry(QRect(240, 10, 681, 551))
        font3 = QFont()
        font3.setPointSize(12)
        self.logBox.setFont(font3)
        self.logBox.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.logText = QPlainTextEdit(self.logBox)
        self.logText.setObjectName(u"logText")
        self.logText.setGeometry(QRect(20, 40, 641, 501))
        font4 = QFont()
        font4.setFamilies([u"Noto Sans Mono"])
        font4.setPointSize(10)
        self.logText.setFont(font4)
        self.logText.setReadOnly(True)
        self.progressBar = QProgressBar(self.logBox)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(30, 60, 391, 21))
        Kleon.setCentralWidget(self.centralwidget)

        self.retranslateUi(Kleon)

        QMetaObject.connectSlotsByName(Kleon)
    # setupUi

    def retranslateUi(self, Kleon):
        Kleon.setWindowTitle(QCoreApplication.translate("Kleon", u"Kleon", None))
        self.opsBox.setTitle(QCoreApplication.translate("Kleon", u"Azioni", None))
        self.dnfOpt.setText(QCoreApplication.translate("Kleon", u"DNF", None))
        self.systemdOpt.setText(QCoreApplication.translate("Kleon", u"Journal systemd", None))
        self.bashOpt.setText(QCoreApplication.translate("Kleon", u"Bash", None))
        self.cacheOpt.setText(QCoreApplication.translate("Kleon", u"Cache Utente", None))
        self.flatpakOpt.setText(QCoreApplication.translate("Kleon", u"Flatpak", None))
        self.coredumpOpt.setText(QCoreApplication.translate("Kleon", u"Core Dump", None))
        self.packagekitOpt.setText(QCoreApplication.translate("Kleon", u"PackageKit", None))
        self.tmpOpt.setText(QCoreApplication.translate("Kleon", u"File Temporanei", None))
        self.logsOpt.setText(QCoreApplication.translate("Kleon", u"Log Obsoleti", None))
        self.abrtOpt.setText(QCoreApplication.translate("Kleon", u"Crash Report", None))
        self.kernelOpt.setText(QCoreApplication.translate("Kleon", u"Kernel Obsoleti", None))
        self.recentOpt.setText(QCoreApplication.translate("Kleon", u"Documenti Recenti", None))
        self.browserOpt.setText(QCoreApplication.translate("Kleon", u"Pulizia Browser", None))
        self.passwordOpt.setText(QCoreApplication.translate("Kleon", u"Elimina Password", None))
        self.logBox.setTitle(QCoreApplication.translate("Kleon", u"Log", None))
    # retranslateUi

